apiVersion: v1
kind: Service
metadata:
  name: frenandi-site-kubernetes-service
  labels:
    app: frenandi-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9090
    targetPort: 80
  selector:
    app: frenandi-site
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frenandi-site
spec:
  replicas: 3
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  selector:
    matchLabels:
      app: frenandi-site
  template:
    metadata:
      labels:
        app: frenandi-site
    spec:
      containers:
      - name: frenandi-site
        image: frenandi/clouddevopscapstoneproject
        imagePullPolicy: Always
        ports:
        - containerPort: 80