apiVersion: apps/v1
kind: Deployment
metadata:
  name: frenandi-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frenandi-site
  template:
    metadata:
      labels:
        app: frenandi-site
    spec:
      containers:
      - name: frenandi-site
        image: "frenandi/clouddevopscapstoneproject:60"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: frenandicred